/**
 * CloudEmotion API v1
 * CrowdEmotion API
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package co.uk.crowdemotion;

import co.uk.crowdemotion.ApiException;
import io.swagger.client.model.Media;
import io.swagger.client.model.MediaCreation;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MediaApi
 */
public class MediaApiTest {

    private final MediaApi api = new MediaApi();

    
    /**
     * Find all registered Media
     *
     * &lt;p&gt;&lt;strong&gt;Permissions:&lt;/strong&gt; ✓ Respondent ✗ Customer ✓ Manager&lt;/p&gt;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void mediaGetTest() throws ApiException {
        Integer skip = null;
        Integer limit = null;
        String where = null;
        String sort = null;
        // Media response = api.mediaGet(skip, limit, where, sort);

        // TODO: test validations
    }
    
    /**
     * Delete Media
     *
     * &lt;p&gt;&lt;strong&gt;Permissions:&lt;/strong&gt; ✗ Respondent ✗ Customer ✓ Manager&lt;/p&gt;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void mediaMediaIdDeleteTest() throws ApiException {
        Integer mediaId = null;
        // String response = api.mediaMediaIdDelete(mediaId);

        // TODO: test validations
    }
    
    /**
     * Find a Media
     *
     * &lt;p&gt;&lt;strong&gt;Permissions:&lt;/strong&gt; ✓ Respondent ✗ Customer ✓ Manager&lt;/p&gt;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void mediaMediaIdGetTest() throws ApiException {
        Integer mediaId = null;
        Boolean presignedUrl = null;
        // List<Media> response = api.mediaMediaIdGet(mediaId, presignedUrl);

        // TODO: test validations
    }
    
    /**
     * Update a Media
     *
     * &lt;p&gt;&lt;strong&gt;Permissions:&lt;/strong&gt; ✗ Respondent ✗ Customer ✓ Manager&lt;/p&gt;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void mediaMediaIdPutTest() throws ApiException {
        Integer mediaId = null;
        MediaCreation body = null;
        // Media response = api.mediaMediaIdPut(mediaId, body);

        // TODO: test validations
    }
    
    /**
     * Create new Media
     *
     * &lt;p&gt;&lt;strong&gt;Permissions:&lt;/strong&gt; ✗ Respondent ✗ Customer ✓ Manager&lt;/p&gt;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void mediaPostTest() throws ApiException {
        MediaCreation body = null;
        // Media response = api.mediaPost(body);

        // TODO: test validations
    }
    
}
