/**
 * CloudEmotion API v1
 * CrowdEmotion API
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package co.uk.crowdemotion;

import co.uk.crowdemotion.ApiException;
import io.swagger.client.model.Response;
import io.swagger.client.model.ResponseCreation;
import io.swagger.client.model.ResponseMetadataResponse;
import io.swagger.client.model.ResponseMetadata;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ResponseApi
 */
public class ResponseApiTest {

    private final ResponseApi api = new ResponseApi();

    
    /**
     * Find all Responses
     *
     * &lt;p&gt;&lt;strong&gt;Permissions:&lt;/strong&gt; ✓ Respondent ✗ Customer ✓ Manager&lt;/p&gt;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void responseGetTest() throws ApiException {
        Integer skip = null;
        Integer limit = null;
        String where = null;
        String sort = null;
        // List<Response> response = api.responseGet(skip, limit, where, sort);

        // TODO: test validations
    }
    
    /**
     * Create a Response
     *
     * &lt;p&gt;&lt;strong&gt;Permissions:&lt;/strong&gt; ✓ Respondent ✗ Customer ✓ Manager&lt;/p&gt;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void responsePostTest() throws ApiException {
        ResponseCreation body = null;
        // Response response = api.responsePost(body);

        // TODO: test validations
    }
    
    /**
     * Delete a Response
     *
     * &lt;p&gt;&lt;strong&gt;Permissions:&lt;/strong&gt; ✗ Respondent ✗ Customer ✓ Manager&lt;/p&gt;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void responseResponseIdDeleteTest() throws ApiException {
        Integer responseId = null;
        // String response = api.responseResponseIdDelete(responseId);

        // TODO: test validations
    }
    
    /**
     * Find a Response
     *
     * &lt;p&gt;&lt;strong&gt;Permissions:&lt;/strong&gt; ✓ Respondent ✗ Customer ✓ Manager&lt;/p&gt;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void responseResponseIdGetTest() throws ApiException {
        Integer responseId = null;
        // Response response = api.responseResponseIdGet(responseId);

        // TODO: test validations
    }
    
    /**
     * Show Response Metadata
     *
     * &lt;p&gt;&lt;strong&gt;Permissions:&lt;/strong&gt; ✓ Respondent ✗ Customer ✓ Manager&lt;/p&gt;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void responseResponseIdMetadataGetTest() throws ApiException {
        Integer responseId = null;
        // ResponseMetadataResponse response = api.responseResponseIdMetadataGet(responseId);

        // TODO: test validations
    }
    
    /**
     * Add Response Metadata
     *
     * &lt;p&gt;&lt;strong&gt;Permissions:&lt;/strong&gt; ✓ Respondent ✗ Customer ✓ Manager&lt;/p&gt;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void responseResponseIdMetadataPostTest() throws ApiException {
        Integer responseId = null;
        ResponseMetadata body = null;
        // ResponseMetadataResponse response = api.responseResponseIdMetadataPost(responseId, body);

        // TODO: test validations
    }
    
    /**
     * Update a Response
     *
     * &lt;p&gt;&lt;strong&gt;Permissions:&lt;/strong&gt; ✓ Respondent ✗ Customer ✓ Manager&lt;/p&gt;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void responseResponseIdPutTest() throws ApiException {
        Integer responseId = null;
        ResponseCreation body = null;
        // Response response = api.responseResponseIdPut(responseId, body);

        // TODO: test validations
    }
    
}
