/**
 * CloudEmotion API v1
 * CrowdEmotion API
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package co.uk.crowdemotion;

import co.uk.crowdemotion.ApiException;
import io.swagger.client.model.Respondent;
import io.swagger.client.model.RespondentMetadataResponse;
import io.swagger.client.model.RespondentMetadata;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RespondentApi
 */
public class RespondentApiTest {

    private final RespondentApi api = new RespondentApi();

    
    /**
     * Find all Respondents of a Research
     *
     * &lt;p&gt;&lt;strong&gt;Permissions:&lt;/strong&gt; ✓ Respondent ✗ Customer ✓ Manager&lt;/p&gt;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void respondentGetTest() throws ApiException {
        Integer researchId = null;
        Integer skip = null;
        Integer limit = null;
        String where = null;
        String sort = null;
        // List<Respondent> response = api.respondentGet(researchId, skip, limit, where, sort);

        // TODO: test validations
    }
    
    /**
     * Create a Respondent
     *
     * &lt;p&gt;&lt;strong&gt;Permissions:&lt;/strong&gt; ✓ Respondent ✗ Customer ✓ Manager&lt;/p&gt;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void respondentPostTest() throws ApiException {
        Respondent body = null;
        // Respondent response = api.respondentPost(body);

        // TODO: test validations
    }
    
    /**
     * Delete a Respondent
     *
     * &lt;p&gt;&lt;strong&gt;Permissions:&lt;/strong&gt; ✗ Respondent ✗ Customer ✓ Manager&lt;/p&gt;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void respondentRespondentIdDeleteTest() throws ApiException {
        Integer respondentId = null;
        // String response = api.respondentRespondentIdDelete(respondentId);

        // TODO: test validations
    }
    
    /**
     * Find a Respondent
     *
     * &lt;p&gt;&lt;strong&gt;Permissions:&lt;/strong&gt; ✓ Respondent ✗ Customer ✓ Manager&lt;/p&gt;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void respondentRespondentIdGetTest() throws ApiException {
        Integer respondentId = null;
        // Respondent response = api.respondentRespondentIdGet(respondentId);

        // TODO: test validations
    }
    
    /**
     * Find Respondent Metadata
     *
     * &lt;p&gt;&lt;strong&gt;Permissions:&lt;/strong&gt; ✓ Respondent ✗ Customer ✓ Manager&lt;/p&gt;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void respondentRespondentIdMetadataGetTest() throws ApiException {
        Integer respondentId = null;
        // RespondentMetadataResponse response = api.respondentRespondentIdMetadataGet(respondentId);

        // TODO: test validations
    }
    
    /**
     * Add Respondent Metadata
     *
     * &lt;p&gt;&lt;strong&gt;Permissions:&lt;/strong&gt; ✓ Respondent ✗ Customer ✓ Manager&lt;/p&gt;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void respondentRespondentIdMetadataPostTest() throws ApiException {
        Integer respondentId = null;
        RespondentMetadata body = null;
        // RespondentMetadataResponse response = api.respondentRespondentIdMetadataPost(respondentId, body);

        // TODO: test validations
    }
    
    /**
     * Update a Respondent
     *
     * &lt;p&gt;&lt;strong&gt;Permissions:&lt;/strong&gt; ✓ Respondent ✗ Customer ✓ Manager&lt;/p&gt;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void respondentRespondentIdPutTest() throws ApiException {
        Integer respondentId = null;
        Respondent body = null;
        // Respondent response = api.respondentRespondentIdPut(respondentId, body);

        // TODO: test validations
    }
    
}
