/**
 * CloudEmotion API v1
 * CrowdEmotion API
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * ContentDetails
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-07-25T14:53:50.872+01:00")
public class ContentDetails   {
  @SerializedName("duration")
  private String duration = null;

  @SerializedName("dimension")
  private String dimension = null;

  @SerializedName("definition")
  private String definition = null;

  @SerializedName("caption")
  private Boolean caption = null;

  @SerializedName("licensedContent")
  private Boolean licensedContent = null;

  public ContentDetails duration(String duration) {
    this.duration = duration;
    return this;
  }

   /**
   * 
   * @return duration
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getDuration() {
    return duration;
  }

  public void setDuration(String duration) {
    this.duration = duration;
  }

  public ContentDetails dimension(String dimension) {
    this.dimension = dimension;
    return this;
  }

   /**
   * 
   * @return dimension
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getDimension() {
    return dimension;
  }

  public void setDimension(String dimension) {
    this.dimension = dimension;
  }

  public ContentDetails definition(String definition) {
    this.definition = definition;
    return this;
  }

   /**
   * 
   * @return definition
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getDefinition() {
    return definition;
  }

  public void setDefinition(String definition) {
    this.definition = definition;
  }

  public ContentDetails caption(Boolean caption) {
    this.caption = caption;
    return this;
  }

   /**
   * 
   * @return caption
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Boolean getCaption() {
    return caption;
  }

  public void setCaption(Boolean caption) {
    this.caption = caption;
  }

  public ContentDetails licensedContent(Boolean licensedContent) {
    this.licensedContent = licensedContent;
    return this;
  }

   /**
   * 
   * @return licensedContent
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Boolean getLicensedContent() {
    return licensedContent;
  }

  public void setLicensedContent(Boolean licensedContent) {
    this.licensedContent = licensedContent;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContentDetails contentDetails = (ContentDetails) o;
    return Objects.equals(this.duration, contentDetails.duration) &&
        Objects.equals(this.dimension, contentDetails.dimension) &&
        Objects.equals(this.definition, contentDetails.definition) &&
        Objects.equals(this.caption, contentDetails.caption) &&
        Objects.equals(this.licensedContent, contentDetails.licensedContent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(duration, dimension, definition, caption, licensedContent);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContentDetails {\n");
    
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    dimension: ").append(toIndentedString(dimension)).append("\n");
    sb.append("    definition: ").append(toIndentedString(definition)).append("\n");
    sb.append("    caption: ").append(toIndentedString(caption)).append("\n");
    sb.append("    licensedContent: ").append(toIndentedString(licensedContent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

