/**
 * CloudEmotion API v1
 * CrowdEmotion API
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * ResearchCreation
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-08-11T15:53:16.377+01:00")
public class ResearchCreation   {
  @SerializedName("title")
  private String title = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("ready")
  private Boolean ready = null;

  @SerializedName("complete")
  private Boolean complete = null;

  @SerializedName("archived")
  private Boolean archived = null;

  @SerializedName("outgoingUrl")
  private String outgoingUrl = null;

  @SerializedName("customData")
  private String customData = null;

  public ResearchCreation title(String title) {
    this.title = title;
    return this;
  }

   /**
   * 
   * @return title
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public ResearchCreation description(String description) {
    this.description = description;
    return this;
  }

   /**
   * 
   * @return description
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ResearchCreation ready(Boolean ready) {
    this.ready = ready;
    return this;
  }

   /**
   * 
   * @return ready
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Boolean getReady() {
    return ready;
  }

  public void setReady(Boolean ready) {
    this.ready = ready;
  }

  public ResearchCreation complete(Boolean complete) {
    this.complete = complete;
    return this;
  }

   /**
   * 
   * @return complete
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Boolean getComplete() {
    return complete;
  }

  public void setComplete(Boolean complete) {
    this.complete = complete;
  }

  public ResearchCreation archived(Boolean archived) {
    this.archived = archived;
    return this;
  }

   /**
   * 
   * @return archived
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Boolean getArchived() {
    return archived;
  }

  public void setArchived(Boolean archived) {
    this.archived = archived;
  }

  public ResearchCreation outgoingUrl(String outgoingUrl) {
    this.outgoingUrl = outgoingUrl;
    return this;
  }

   /**
   * 
   * @return outgoingUrl
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getOutgoingUrl() {
    return outgoingUrl;
  }

  public void setOutgoingUrl(String outgoingUrl) {
    this.outgoingUrl = outgoingUrl;
  }

  public ResearchCreation customData(String customData) {
    this.customData = customData;
    return this;
  }

   /**
   * 
   * @return customData
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getCustomData() {
    return customData;
  }

  public void setCustomData(String customData) {
    this.customData = customData;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResearchCreation researchCreation = (ResearchCreation) o;
    return Objects.equals(this.title, researchCreation.title) &&
        Objects.equals(this.description, researchCreation.description) &&
        Objects.equals(this.ready, researchCreation.ready) &&
        Objects.equals(this.complete, researchCreation.complete) &&
        Objects.equals(this.archived, researchCreation.archived) &&
        Objects.equals(this.outgoingUrl, researchCreation.outgoingUrl) &&
        Objects.equals(this.customData, researchCreation.customData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, description, ready, complete, archived, outgoingUrl, customData);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResearchCreation {\n");
    
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    ready: ").append(toIndentedString(ready)).append("\n");
    sb.append("    complete: ").append(toIndentedString(complete)).append("\n");
    sb.append("    archived: ").append(toIndentedString(archived)).append("\n");
    sb.append("    outgoingUrl: ").append(toIndentedString(outgoingUrl)).append("\n");
    sb.append("    customData: ").append(toIndentedString(customData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

