/**
 * CloudEmotion API v1
 * CrowdEmotion API
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Stats;
import org.joda.time.DateTime;


/**
 * Research
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-08-11T15:53:16.377+01:00")
public class Research   {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("timeCreated")
  private DateTime timeCreated = null;

  @SerializedName("uuid")
  private String uuid = null;

  @SerializedName("key")
  private String key = null;

  @SerializedName("title")
  private String title = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("ready")
  private Boolean ready = null;

  @SerializedName("complete")
  private Boolean complete = null;

  @SerializedName("archived")
  private Boolean archived = null;

  @SerializedName("outgoingUrl")
  private String outgoingUrl = null;

  @SerializedName("customData")
  private String customData = null;

  @SerializedName("owner_id")
  private Integer ownerId = null;

  @SerializedName("company_id")
  private Integer companyId = null;

  @SerializedName("stats")
  private Stats stats = null;

  public Research id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * 
   * @return id
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Research timeCreated(DateTime timeCreated) {
    this.timeCreated = timeCreated;
    return this;
  }

   /**
   * 
   * @return timeCreated
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public DateTime getTimeCreated() {
    return timeCreated;
  }

  public void setTimeCreated(DateTime timeCreated) {
    this.timeCreated = timeCreated;
  }

  public Research uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * 
   * @return uuid
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }

  public Research key(String key) {
    this.key = key;
    return this;
  }

   /**
   * 
   * @return key
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getKey() {
    return key;
  }

  public void setKey(String key) {
    this.key = key;
  }

  public Research title(String title) {
    this.title = title;
    return this;
  }

   /**
   * 
   * @return title
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public Research description(String description) {
    this.description = description;
    return this;
  }

   /**
   * 
   * @return description
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Research ready(Boolean ready) {
    this.ready = ready;
    return this;
  }

   /**
   * 
   * @return ready
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Boolean getReady() {
    return ready;
  }

  public void setReady(Boolean ready) {
    this.ready = ready;
  }

  public Research complete(Boolean complete) {
    this.complete = complete;
    return this;
  }

   /**
   * 
   * @return complete
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Boolean getComplete() {
    return complete;
  }

  public void setComplete(Boolean complete) {
    this.complete = complete;
  }

  public Research archived(Boolean archived) {
    this.archived = archived;
    return this;
  }

   /**
   * 
   * @return archived
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Boolean getArchived() {
    return archived;
  }

  public void setArchived(Boolean archived) {
    this.archived = archived;
  }

  public Research outgoingUrl(String outgoingUrl) {
    this.outgoingUrl = outgoingUrl;
    return this;
  }

   /**
   * 
   * @return outgoingUrl
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getOutgoingUrl() {
    return outgoingUrl;
  }

  public void setOutgoingUrl(String outgoingUrl) {
    this.outgoingUrl = outgoingUrl;
  }

  public Research customData(String customData) {
    this.customData = customData;
    return this;
  }

   /**
   * 
   * @return customData
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getCustomData() {
    return customData;
  }

  public void setCustomData(String customData) {
    this.customData = customData;
  }

  public Research ownerId(Integer ownerId) {
    this.ownerId = ownerId;
    return this;
  }

   /**
   * 
   * @return ownerId
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Integer getOwnerId() {
    return ownerId;
  }

  public void setOwnerId(Integer ownerId) {
    this.ownerId = ownerId;
  }

  public Research companyId(Integer companyId) {
    this.companyId = companyId;
    return this;
  }

   /**
   * 
   * @return companyId
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Integer getCompanyId() {
    return companyId;
  }

  public void setCompanyId(Integer companyId) {
    this.companyId = companyId;
  }

  public Research stats(Stats stats) {
    this.stats = stats;
    return this;
  }

   /**
   * Get stats
   * @return stats
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Stats getStats() {
    return stats;
  }

  public void setStats(Stats stats) {
    this.stats = stats;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Research research = (Research) o;
    return Objects.equals(this.id, research.id) &&
        Objects.equals(this.timeCreated, research.timeCreated) &&
        Objects.equals(this.uuid, research.uuid) &&
        Objects.equals(this.key, research.key) &&
        Objects.equals(this.title, research.title) &&
        Objects.equals(this.description, research.description) &&
        Objects.equals(this.ready, research.ready) &&
        Objects.equals(this.complete, research.complete) &&
        Objects.equals(this.archived, research.archived) &&
        Objects.equals(this.outgoingUrl, research.outgoingUrl) &&
        Objects.equals(this.customData, research.customData) &&
        Objects.equals(this.ownerId, research.ownerId) &&
        Objects.equals(this.companyId, research.companyId) &&
        Objects.equals(this.stats, research.stats);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, timeCreated, uuid, key, title, description, ready, complete, archived, outgoingUrl, customData, ownerId, companyId, stats);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Research {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    timeCreated: ").append(toIndentedString(timeCreated)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    ready: ").append(toIndentedString(ready)).append("\n");
    sb.append("    complete: ").append(toIndentedString(complete)).append("\n");
    sb.append("    archived: ").append(toIndentedString(archived)).append("\n");
    sb.append("    outgoingUrl: ").append(toIndentedString(outgoingUrl)).append("\n");
    sb.append("    customData: ").append(toIndentedString(customData)).append("\n");
    sb.append("    ownerId: ").append(toIndentedString(ownerId)).append("\n");
    sb.append("    companyId: ").append(toIndentedString(companyId)).append("\n");
    sb.append("    stats: ").append(toIndentedString(stats)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

