/**
 * CloudEmotion API v1
 * CrowdEmotion API
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Data;


/**
 * RespondentMetadataResponse
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-08-11T15:53:16.377+01:00")
public class RespondentMetadataResponse   {
  @SerializedName("respondentId")
  private String respondentId = null;

  @SerializedName("data")
  private Data data = null;

  public RespondentMetadataResponse respondentId(String respondentId) {
    this.respondentId = respondentId;
    return this;
  }

   /**
   * 
   * @return respondentId
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getRespondentId() {
    return respondentId;
  }

  public void setRespondentId(String respondentId) {
    this.respondentId = respondentId;
  }

  public RespondentMetadataResponse data(Data data) {
    this.data = data;
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Data getData() {
    return data;
  }

  public void setData(Data data) {
    this.data = data;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RespondentMetadataResponse respondentMetadataResponse = (RespondentMetadataResponse) o;
    return Objects.equals(this.respondentId, respondentMetadataResponse.respondentId) &&
        Objects.equals(this.data, respondentMetadataResponse.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(respondentId, data);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RespondentMetadataResponse {\n");
    
    sb.append("    respondentId: ").append(toIndentedString(respondentId)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

