/**
 * CloudEmotion API v1
 * CrowdEmotion API
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;


/**
 * Response
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-07-25T14:53:50.872+01:00")
public class Response   {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("timeCreated")
  private DateTime timeCreated = null;

  @SerializedName("researchId")
  private Integer researchId = null;

  @SerializedName("mediaId")
  private Integer mediaId = null;

  @SerializedName("respondentId")
  private Integer respondentId = null;

  @SerializedName("userId")
  private Integer userId = null;

  @SerializedName("complete")
  private Boolean complete = null;

  @SerializedName("used")
  private Boolean used = null;

  @SerializedName("company_id")
  private Integer companyId = null;

  public Response id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * 
   * @return id
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Response timeCreated(DateTime timeCreated) {
    this.timeCreated = timeCreated;
    return this;
  }

   /**
   * 
   * @return timeCreated
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public DateTime getTimeCreated() {
    return timeCreated;
  }

  public void setTimeCreated(DateTime timeCreated) {
    this.timeCreated = timeCreated;
  }

  public Response researchId(Integer researchId) {
    this.researchId = researchId;
    return this;
  }

   /**
   * 
   * @return researchId
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Integer getResearchId() {
    return researchId;
  }

  public void setResearchId(Integer researchId) {
    this.researchId = researchId;
  }

  public Response mediaId(Integer mediaId) {
    this.mediaId = mediaId;
    return this;
  }

   /**
   * 
   * @return mediaId
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Integer getMediaId() {
    return mediaId;
  }

  public void setMediaId(Integer mediaId) {
    this.mediaId = mediaId;
  }

  public Response respondentId(Integer respondentId) {
    this.respondentId = respondentId;
    return this;
  }

   /**
   * 
   * @return respondentId
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Integer getRespondentId() {
    return respondentId;
  }

  public void setRespondentId(Integer respondentId) {
    this.respondentId = respondentId;
  }

  public Response userId(Integer userId) {
    this.userId = userId;
    return this;
  }

   /**
   * 
   * @return userId
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Integer getUserId() {
    return userId;
  }

  public void setUserId(Integer userId) {
    this.userId = userId;
  }

  public Response complete(Boolean complete) {
    this.complete = complete;
    return this;
  }

   /**
   * 
   * @return complete
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Boolean getComplete() {
    return complete;
  }

  public void setComplete(Boolean complete) {
    this.complete = complete;
  }

  public Response used(Boolean used) {
    this.used = used;
    return this;
  }

   /**
   * 
   * @return used
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Boolean getUsed() {
    return used;
  }

  public void setUsed(Boolean used) {
    this.used = used;
  }

  public Response companyId(Integer companyId) {
    this.companyId = companyId;
    return this;
  }

   /**
   * 
   * @return companyId
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Integer getCompanyId() {
    return companyId;
  }

  public void setCompanyId(Integer companyId) {
    this.companyId = companyId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Response response = (Response) o;
    return Objects.equals(this.id, response.id) &&
        Objects.equals(this.timeCreated, response.timeCreated) &&
        Objects.equals(this.researchId, response.researchId) &&
        Objects.equals(this.mediaId, response.mediaId) &&
        Objects.equals(this.respondentId, response.respondentId) &&
        Objects.equals(this.userId, response.userId) &&
        Objects.equals(this.complete, response.complete) &&
        Objects.equals(this.used, response.used) &&
        Objects.equals(this.companyId, response.companyId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, timeCreated, researchId, mediaId, respondentId, userId, complete, used, companyId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Response {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    timeCreated: ").append(toIndentedString(timeCreated)).append("\n");
    sb.append("    researchId: ").append(toIndentedString(researchId)).append("\n");
    sb.append("    mediaId: ").append(toIndentedString(mediaId)).append("\n");
    sb.append("    respondentId: ").append(toIndentedString(respondentId)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    complete: ").append(toIndentedString(complete)).append("\n");
    sb.append("    used: ").append(toIndentedString(used)).append("\n");
    sb.append("    companyId: ").append(toIndentedString(companyId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

