/**
 * CloudEmotion API v1
 * CrowdEmotion API
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * Status
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-07-25T14:53:50.872+01:00")
public class Status   {
  @SerializedName("uploadStatus")
  private String uploadStatus = null;

  @SerializedName("privacyStatus")
  private String privacyStatus = null;

  @SerializedName("license")
  private String license = null;

  @SerializedName("embeddable")
  private String embeddable = null;

  @SerializedName("publicStatsViewable")
  private String publicStatsViewable = null;

  public Status uploadStatus(String uploadStatus) {
    this.uploadStatus = uploadStatus;
    return this;
  }

   /**
   * 
   * @return uploadStatus
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getUploadStatus() {
    return uploadStatus;
  }

  public void setUploadStatus(String uploadStatus) {
    this.uploadStatus = uploadStatus;
  }

  public Status privacyStatus(String privacyStatus) {
    this.privacyStatus = privacyStatus;
    return this;
  }

   /**
   * 
   * @return privacyStatus
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getPrivacyStatus() {
    return privacyStatus;
  }

  public void setPrivacyStatus(String privacyStatus) {
    this.privacyStatus = privacyStatus;
  }

  public Status license(String license) {
    this.license = license;
    return this;
  }

   /**
   * 
   * @return license
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getLicense() {
    return license;
  }

  public void setLicense(String license) {
    this.license = license;
  }

  public Status embeddable(String embeddable) {
    this.embeddable = embeddable;
    return this;
  }

   /**
   * 
   * @return embeddable
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getEmbeddable() {
    return embeddable;
  }

  public void setEmbeddable(String embeddable) {
    this.embeddable = embeddable;
  }

  public Status publicStatsViewable(String publicStatsViewable) {
    this.publicStatsViewable = publicStatsViewable;
    return this;
  }

   /**
   * 
   * @return publicStatsViewable
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getPublicStatsViewable() {
    return publicStatsViewable;
  }

  public void setPublicStatsViewable(String publicStatsViewable) {
    this.publicStatsViewable = publicStatsViewable;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Status status = (Status) o;
    return Objects.equals(this.uploadStatus, status.uploadStatus) &&
        Objects.equals(this.privacyStatus, status.privacyStatus) &&
        Objects.equals(this.license, status.license) &&
        Objects.equals(this.embeddable, status.embeddable) &&
        Objects.equals(this.publicStatsViewable, status.publicStatsViewable);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uploadStatus, privacyStatus, license, embeddable, publicStatsViewable);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Status {\n");
    
    sb.append("    uploadStatus: ").append(toIndentedString(uploadStatus)).append("\n");
    sb.append("    privacyStatus: ").append(toIndentedString(privacyStatus)).append("\n");
    sb.append("    license: ").append(toIndentedString(license)).append("\n");
    sb.append("    embeddable: ").append(toIndentedString(embeddable)).append("\n");
    sb.append("    publicStatsViewable: ").append(toIndentedString(publicStatsViewable)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

