/**
 * CloudEmotion API v1
 * CrowdEmotion API
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * Statistics
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-08-11T15:53:16.377+01:00")
public class Statistics   {
  @SerializedName("viewCount")
  private Integer viewCount = null;

  @SerializedName("likeCount")
  private Integer likeCount = null;

  @SerializedName("dislikeCount")
  private Integer dislikeCount = null;

  @SerializedName("favoriteCount")
  private Integer favoriteCount = null;

  @SerializedName("commentCount")
  private Integer commentCount = null;

  public Statistics viewCount(Integer viewCount) {
    this.viewCount = viewCount;
    return this;
  }

   /**
   * 
   * @return viewCount
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Integer getViewCount() {
    return viewCount;
  }

  public void setViewCount(Integer viewCount) {
    this.viewCount = viewCount;
  }

  public Statistics likeCount(Integer likeCount) {
    this.likeCount = likeCount;
    return this;
  }

   /**
   * 
   * @return likeCount
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Integer getLikeCount() {
    return likeCount;
  }

  public void setLikeCount(Integer likeCount) {
    this.likeCount = likeCount;
  }

  public Statistics dislikeCount(Integer dislikeCount) {
    this.dislikeCount = dislikeCount;
    return this;
  }

   /**
   * 
   * @return dislikeCount
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Integer getDislikeCount() {
    return dislikeCount;
  }

  public void setDislikeCount(Integer dislikeCount) {
    this.dislikeCount = dislikeCount;
  }

  public Statistics favoriteCount(Integer favoriteCount) {
    this.favoriteCount = favoriteCount;
    return this;
  }

   /**
   * 
   * @return favoriteCount
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Integer getFavoriteCount() {
    return favoriteCount;
  }

  public void setFavoriteCount(Integer favoriteCount) {
    this.favoriteCount = favoriteCount;
  }

  public Statistics commentCount(Integer commentCount) {
    this.commentCount = commentCount;
    return this;
  }

   /**
   * 
   * @return commentCount
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Integer getCommentCount() {
    return commentCount;
  }

  public void setCommentCount(Integer commentCount) {
    this.commentCount = commentCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Statistics statistics = (Statistics) o;
    return Objects.equals(this.viewCount, statistics.viewCount) &&
        Objects.equals(this.likeCount, statistics.likeCount) &&
        Objects.equals(this.dislikeCount, statistics.dislikeCount) &&
        Objects.equals(this.favoriteCount, statistics.favoriteCount) &&
        Objects.equals(this.commentCount, statistics.commentCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(viewCount, likeCount, dislikeCount, favoriteCount, commentCount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Statistics {\n");
    
    sb.append("    viewCount: ").append(toIndentedString(viewCount)).append("\n");
    sb.append("    likeCount: ").append(toIndentedString(likeCount)).append("\n");
    sb.append("    dislikeCount: ").append(toIndentedString(dislikeCount)).append("\n");
    sb.append("    favoriteCount: ").append(toIndentedString(favoriteCount)).append("\n");
    sb.append("    commentCount: ").append(toIndentedString(commentCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

