/**
 * CloudEmotion API v1
 * CrowdEmotion API
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;


/**
 * Tags
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-08-11T15:53:16.377+01:00")
public class Tags   {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("duration")
  private Integer duration = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("t")
  private Integer t = null;

  @SerializedName("x")
  private String x = null;

  @SerializedName("y")
  private String y = null;

  @SerializedName("media_id")
  private Integer mediaId = null;

  @SerializedName("timeCreated")
  private DateTime timeCreated = null;

  @SerializedName("uuid")
  private String uuid = null;

  @SerializedName("version")
  private Integer version = null;

  @SerializedName("created")
  private Boolean created = null;

  @SerializedName("modified")
  private Boolean modified = null;

  public Tags id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * 
   * @return id
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Tags duration(Integer duration) {
    this.duration = duration;
    return this;
  }

   /**
   * 
   * @return duration
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Integer getDuration() {
    return duration;
  }

  public void setDuration(Integer duration) {
    this.duration = duration;
  }

  public Tags name(String name) {
    this.name = name;
    return this;
  }

   /**
   * 
   * @return name
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Tags t(Integer t) {
    this.t = t;
    return this;
  }

   /**
   * 
   * @return t
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Integer getT() {
    return t;
  }

  public void setT(Integer t) {
    this.t = t;
  }

  public Tags x(String x) {
    this.x = x;
    return this;
  }

   /**
   * 
   * @return x
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getX() {
    return x;
  }

  public void setX(String x) {
    this.x = x;
  }

  public Tags y(String y) {
    this.y = y;
    return this;
  }

   /**
   * 
   * @return y
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getY() {
    return y;
  }

  public void setY(String y) {
    this.y = y;
  }

  public Tags mediaId(Integer mediaId) {
    this.mediaId = mediaId;
    return this;
  }

   /**
   * 
   * @return mediaId
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Integer getMediaId() {
    return mediaId;
  }

  public void setMediaId(Integer mediaId) {
    this.mediaId = mediaId;
  }

  public Tags timeCreated(DateTime timeCreated) {
    this.timeCreated = timeCreated;
    return this;
  }

   /**
   * 
   * @return timeCreated
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public DateTime getTimeCreated() {
    return timeCreated;
  }

  public void setTimeCreated(DateTime timeCreated) {
    this.timeCreated = timeCreated;
  }

  public Tags uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * 
   * @return uuid
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }

  public Tags version(Integer version) {
    this.version = version;
    return this;
  }

   /**
   * 
   * @return version
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Integer getVersion() {
    return version;
  }

  public void setVersion(Integer version) {
    this.version = version;
  }

  public Tags created(Boolean created) {
    this.created = created;
    return this;
  }

   /**
   * 
   * @return created
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Boolean getCreated() {
    return created;
  }

  public void setCreated(Boolean created) {
    this.created = created;
  }

  public Tags modified(Boolean modified) {
    this.modified = modified;
    return this;
  }

   /**
   * 
   * @return modified
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Boolean getModified() {
    return modified;
  }

  public void setModified(Boolean modified) {
    this.modified = modified;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Tags tags = (Tags) o;
    return Objects.equals(this.id, tags.id) &&
        Objects.equals(this.duration, tags.duration) &&
        Objects.equals(this.name, tags.name) &&
        Objects.equals(this.t, tags.t) &&
        Objects.equals(this.x, tags.x) &&
        Objects.equals(this.y, tags.y) &&
        Objects.equals(this.mediaId, tags.mediaId) &&
        Objects.equals(this.timeCreated, tags.timeCreated) &&
        Objects.equals(this.uuid, tags.uuid) &&
        Objects.equals(this.version, tags.version) &&
        Objects.equals(this.created, tags.created) &&
        Objects.equals(this.modified, tags.modified);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, duration, name, t, x, y, mediaId, timeCreated, uuid, version, created, modified);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Tags {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    t: ").append(toIndentedString(t)).append("\n");
    sb.append("    x: ").append(toIndentedString(x)).append("\n");
    sb.append("    y: ").append(toIndentedString(y)).append("\n");
    sb.append("    mediaId: ").append(toIndentedString(mediaId)).append("\n");
    sb.append("    timeCreated: ").append(toIndentedString(timeCreated)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

